---
title: Bouw een LAMP-webserver met WordPress
hero_image: images/banner.png
description: Stel een lokale server in voor een website op je Raspberry Pi
original_url: https://raspberrypi.org/learning/lamp-web-server-with-wordpress
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 3, design-0, programming-3, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: raspberry-pi, html-css-javascript
site_areas: projects
hardware: raspberry-pi
software: html-css-javascript
version: 4
last_tested: 2017-01-01
steps:
- title: Inleiding
- title: Wat heb je nodig
- title: Stel een Apache-webserver in
- title: Installeer PHP
  completion:
  - engaged
- title: Installeer MySQL
- title: Download WordPress
- title: Stel je WordPress-database in
- title: WordPress-configuratie
  completion:
  - internal
- title: Wat kun je verder nog doen?
