---
title: Zbuduj serwer WWW LAMP za pomocą WordPress
hero_image: images / banner.png
description: Skonfiguruj lokalny serwer dla strony internetowej na swoim Raspberry Pi
original_url: https://raspberrypi.org/learning/lamp-web-server-with-wordpress
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 3, design-0, programming-3, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: raspberry-pi, html-css-javascript
site_areas: projekty
hardware: raspberry-pi
software: html-css-javascript
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Wprowadzenie
  - 
    title: Set up an Apache web server
    completion:
      - engaged
  - 
    title: Install PHP
  - 
    title: Install MariaDB
  - 
    title: Download WordPress
  - 
    title: Set up your WordPress database
    completion:
      - internal
  - 
    title: WordPress configuration
    completion:
      - external
  - 
    title: Challenge
    challenge: true
  - 
    title: What can you do now?
