---
title: Δημιούργησε έναν Διακομιστή Ιστού LAMP με WordPress
hero_image: images/banner.png
description: Ρύθμισε έναν τοπικό διακομιστή για έναν ιστότοπο στο Raspberry Pi
original_url: https://raspberrypi.org/learning/lamp-web-server-with-wordpress
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 3, design-0, programming-3, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: raspberry-pi, html-css-javascript
site_areas: projects
hardware: raspberry-pi
software: html-css-javascript
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Εισαγωγή
  - 
    title: Τι θα χρειαστείς
  - 
    title: Ρύθμισε ένα διακομιστή ιστού Apache
  - 
    title: Εγκατέστησε την PHP
  - 
    title: Εγκατέστησε την MySQL
  - 
    title: Κάνε λήψη του WordPress
  - 
    title: Ρύθμισε την βάση δεδομένων του WordPress σου
  - 
    title: Διαμόρφωση του WordPress
  - 
    title: Και τώρα;
