---
title: Créer un serveur Web LAMP avec WordPress
hero_image: images/banner.png
description: Configurer un serveur local pour un site Web sur ton Raspberry Pi
original_url: https://raspberrypi.org/learning/lamp-web-server-with-wordpress
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 3, design-0, programming-3, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: raspberry-pi, html-css-javascript
site_areas: projects
hardware: raspberry-pi
software: html-css-javascript
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Introduction
  - 
    title: Ce dont tu auras besoin
  - 
    title: Configurer un serveur Web Apache
  - 
    title: Installer PHP
    completion:
      - engagé
  - 
    title: Installer MySQL
  - 
    title: Télécharger WordPress
  - 
    title: Configure ta base de données WordPress
  - 
    title: Configuration de WordPress
    completion:
      - interne
  - 
    title: Et ensuite ?
