---
title: Build a LAMP Web Server with WordPress
hero_image: images/banner.png
description: Set up a local server for a website on your Raspberry Pi
original_url: https://raspberrypi.org/learning/lamp-web-server-with-wordpress
theme: turkuaz
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 3, tasarım-0, programlama-3, fiziksel-hesaplama-0, üretim-0, topluluk-0
interests: ''
technologies: raspberry-pi, html-css-javascript
site_areas: projeler
hardware: raspberry-pi
software: html-css-javascript
version: 4
last_tested: 01/01/2017
steps:
  - 
    title: Giriş
  - 
    title: Set up an Apache web server
    completion:
      - engaged
  - 
    title: Install PHP
  - 
    title: Install MariaDB
  - 
    title: Download WordPress
  - 
    title: Set up your WordPress database
    completion:
      - internal
  - 
    title: WordPress configuration
    completion:
      - external
  - 
    title: Challenge
    challenge: true
  - 
    title: What can you do now?
